[WIP] add cert inspection command
gmeghnag/omc pull request #85
Opened 2023-04-18 11:57 UTC by bverschueren

This adds an `omc certs inspect` command inspired by the similar command in https://github.com/openshift/cluster-debug-tools. Unfortunately importing it directly causes a dependency hell since we're using different versions of apimachinery and since cluster-debug-tools is not meant to be relied on I'm porting the logic here.

To get here, the relevant get(configmap/secret/csr) functions are refactored for re-usability (... and testability perhaps if we agree to take the same path for other getters).

@gmeghnag let me know what you think

2023-04-19 16:46 UTC, gmeghnag requested changes
Ok to implement `omc certs` subcommand, very useful!

**BUT** these changes are breaking something in the way the resources are returned when using `-o json | yaml` with `omc get cm/secret/csr`.

Before:
```
$ omc get -n tester secret  -o json | jq '.items | length' 
8
```

After:
```
omc get -n tester secret  -o json | jq '.items | length'
jq: error (at <stdin>:478): Cannot index array with string "items"
```



P.S.: I used [this](https://drive.google.com/drive/folders/1toLpjbyixZ_u0QkAjzSJBQktW_hjgRFq?usp=share_link) inspect folder to test the commands.

2023-04-19 16:46 UTC, gmeghnag commented on cmd/get/core/secrets.go
Something is breaking the use of `omc get secret/cm/csr`

Before:
```
$ omc get -n tester secret  -o json | jq '.items | length' 
8
```

After:
```
omc get -n tester secret  -o json | jq '.items | length'
jq: error (at <stdin>:478): Cannot index array with string "items"
```



P.S.: I used [this](https://drive.google.com/drive/folders/1toLpjbyixZ_u0QkAjzSJBQktW_hjgRFq?usp=share_link) inspect folder to test the commands.

2023-04-20 11:44 UTC, bverschueren commented on cmd/get/core/secrets.go
Right, we're using (ConfigMaps|Secrets)List structs to return in omc while I was basing on oc output.
This should be in line with the current behaviour now:
```
$ go run main.go get -n tester secret  -o json | jq '.items | length' 
8
$ go run main.go get -n tester cm  -o json | jq '.items | length' 
4
$ git checkout certs-inspect
$ go run main.go get -n tester cm config-service-cabundle -o json > /tmp/w_resourcename.json                                                                                             
$ go run main.go get -n tester cm -o json > /tmp/wo_resourcename.json
$ git checkout main
$ go run main.go get -n tester cm -o json |diff -s /tmp/wo_resourcename.json -
Files /tmp/wo_resourcename.json and - are identical
$ go run main.go get -n tester cm config-service-cabundle -o json| diff -s /tmp/w_resourcename.json -    
Files /tmp/w_resourcename.json and - are identical
```
However yaml output is hosed now; will check it out later.

2023-05-02 07:25 UTC, gmeghnag approved these changes

2023-05-02 07:25 UTC, merged